# To use this file, insall the REST Client extension
# vscode:extension/humao.rest-client

# To switch environments:
#  - Ctrl+Alt+E(Cmd+Alt+E for macOS)
#  - Or `Rest Client: Switch Environment` from command palette

# You'll need to switch to either `local` or `vercel` to get started.

@baseUrl = {{host}}/api
@belt = {{SHOW_INDEX.response.body.0.belt}}
@type = {{SHOW_INDEX.response.body.0.type}}
@name = {{SHOW_INDEX.response.body.0.name}}


# @name SHOW_INDEX
GET {{baseUrl}}
###

# @name SHOW_BELT
GET {{baseUrl}}/{{belt}}
###

# @name SHOW_BELT_EXAMPLE
GET {{baseUrl}}/yellow
###

# @name SHOW_TYPE
GET {{baseUrl}}/type/{{type}}
###

# @name SHOW_TYPE_EXAMPLE
GET {{baseUrl}}/type/Nage-Waza
###

# @name SHOW_NAME
GET {{baseUrl}}/name/{{name}}
###

# @name SHOW_NAME_EXAMPLE
GET {{baseUrl}}/name/Uchi-mata
###

# @name CREATE_JUDO
POST {{baseUrl}}
Content-Type: application/json

  {
    "name": "O-uchi-gari",
    "belt": "yellow",
    "type": "Nage-Waza",
    "img": "https://i.imgur.com/IuGV2Bs.gif"
  }
###

# @name UPDATE_JUDO_EXAMPLE
PATCH {{baseUrl}}/O-uchi-gari
Content-Type: application/json

{
  "name": "O-soto-otoshi",
  "belt": "yellow",
  "type": "Nage-Waza",
  "img": "https://i.imgur.com/UWYHo4N.gif"
}
###

# @name DELETE_JUDO_EXAMPLE
DELETE {{baseUrl}}/O-uchi-gari
###

# @name REGISTER_USER
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "Ryoji Kaji",
  "DOB": "06/17/85",
  "username": "007",
  "email": "wateringMelons@tokyo3mail.com",
  "password": "aReallyGoodPassword"
}